### ISSUE TITLE
Don't lint unsaved files

### ISSUE THREAD

**Issue by Stanzilla** [errata-ai/vale-vscode#101]
Currently the extension tries to lint unsaved files but it can't, so it shows a notification every time that says "please save", which is really annoying. Could we please get an option to turn this off?

**Comment by apupier** [comment]
proposal:
- provide 2 buttons: one to `Abort` and `Abort and Do not Show Again`

something similar than https://github.com/microsoft/vscode/blob/fa4ff1519d9d10f015e7386dc1d727a2ff97c8d0/extensions/git/src/main.ts#L255-L265

The code to change is here https://github.com/errata-ai/vale-vscode/blob/master/src/features/vsUtils.ts#L87

**Comment by apupier** [comment]
@Stanzilla Can you provide specific steps to reproduce please? (i'm unable to reproduce)

**Comment by apupier** [comment]
with steps to reproduce, this branch might be used as a base to fix it https://github.com/apupier/vale-vscode/tree/101-avoidPleaseSaveAllTheTime

**Comment by Stanzilla** [comment]
> @Stanzilla Can you provide specific steps to reproduce please? (i'm unable to reproduce)

Double click the tab bar to create a new "file". Type something in there but don't save. Notice how it has a white circle next to the name in the tab which means "unsaved". Then press ctrl+r to reload the window
