### ISSUE TITLE
Restrict vale to a certain folder

### ISSUE THREAD

**Issue by max-allan-surevine** [errata-ai/vale-vscode#119]
I installed the plugin and started editing docs/file.md. And it worked fine.

Then I went to src/file.ts and Vale is throwing a total fit over trying to lint typescript code.
eg
- `variableName` : Did you really mean variableName?
- `ec2.runInstances(params)` : Use parentheses judiciously.
- `parameter.value` : 'r.V' should have one space.

And so on.

Why is it even trying to run outside comments? But we don't really want it to run on src/** at all. Just docs/**

**Comment by jdkato** [comment]
You control this in your `.vale.ini` file:

```
StylesPath = styles

MinAlertLevel = suggestion

[*.md]
# only Markdown files, for example 
BasedOnStyles = Vale
```
