### ISSUE TITLE
Naming and spelling of VS Code

### ISSUE THREAD

**Issue by thernstig** [errata-ai/vale-vscode#127]
As this is an extension to help with spelling, I felt it was important to bring this forth.

The text in the README as well as the actual extension name as seen in VS Code uses various (and incorrect) spellings. Some say the correct "VS Code" but in many places the incorrect "VScode" is used.

**README**
![image](https://user-images.githubusercontent.com/30827238/231381197-8b30ae83-6e4c-469c-b71a-520f876fc793.png)

**Extension name**
![image](https://user-images.githubusercontent.com/30827238/231381260-fdf5eeff-e877-4644-b819-351ee3073f84.png)

It should be spelled _**VS Code**_ in all places.

**Comment by ChrisChinchilla** [comment]
@thernstig Actually this extension has nothing directly to do with spelling, and is also now deprecated, the new version (https://github.com/ChrisChinchilla/vale-vscode) does have spelling support, some typos in the read me are fixed, and now we have solved the technical issues of the naming change (that you can find in the issues in this repo), we can move forward to fix the rest. Adding spelling support and getting the naming sorted was actually a lot of work, and this is a volunteer project.

Also, as these are relatively small fixes, feel free to make a PR to fix them (on the new repo), thanks!

**Comment by thernstig** [comment]
@ChrisChinchilla I had both repos open and accidentally added the issue here.
