### ISSUE TITLE
Getting "Error: not found: vale" when opening Markdown file

### ISSUE THREAD

**Issue by pedrosousa** [errata-ai/vale-vscode#17]
Hi,

I get this error on VSCode for Windows (x64, user install):

![image](https://user-images.githubusercontent.com/680496/91312948-b5e07a00-e7ac-11ea-8093-7c21b4b612e0.png)

This seems to be due to the `pathExt` argument in the following code, stating that executable files to be considered while running `which` are just the ones with `.cmd` extension:

```typescript
return which.sync("vale", { pathExt: ".cmd" });
```

(in [vsProvider.ts](https://github.com/errata-ai/vale-vscode/blob/master/src/features/vsProvider.ts#L53))

Is there a reason for overriding the `PATHEXT` environment variable while searching for the Vale executable? It breaks things on Windows... unless I do one of the following:
* Create a `vale.cmd` file next to `vale.exe` that simply calls the EXE with all received parameters.
* Remove `, { pathExt: ".cmd" }` from the code and rebuild the extension. This causes the `which` call to consider the current value of the `PATHEXT` environment variable, which in my case is `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW`.

Notes:
* I use a manual installation of `vale.exe`, placing the executable in a folder that is in my `PATH` environment variable. I also tried using the `vale` Chocolatey package, but the problem remains the same: there's no `vale.cmd` available, only `vale.exe`.

* I'm in the process of replacing the previous VSCode extension `testthedocs.vale` with this one from errata.ai. Everything was working properly with the previous extension. Using the `vale.valeCLI.path` setting is not an option because I want to commit the workspace settings file and everyone in my team will have different CLI paths.

Thanks!

**Comment by jdkato** [comment]
This section of code actually *came from* `testthedocs.vale`, so @ChrisChinchilla may be able to speak to its purpose.

The reason it worked for you over there (I'm assuming since I don't use Windows myself) is because that extension set its equivalent of `vale.valeCLI.path` to `vale` by default, which meant that you needed to explicitly make it empty on other platforms.

I think the solution here is to keep `vale.valeCLI.path` empty by default and remove the `pathExt` argument.

**Comment by ChrisChinchilla** [comment]
@pedrosousa I have a windows VM I can test on. So let us know if that does work for you, and if so I'll see what we need to change/document for a future release, as I know the extension has a few windows users

**Comment by jdkato** [comment]
I was able to test my purposed solution on my Vale Server VM and it does indeed seem to work, so I pushed a new release for now.

I'm still open to discussing other options, though, because it seems like this was deliberately added it https://github.com/testthedocs/vscode-vale/pull/12.

**Comment by pedrosousa** [comment]
From my previous tests, removing the `pathExt` argument was enough. I'll test it again tomorrow.

I believe that the `pathExt` was required in the flow VSCode extension (probably this one: https://github.com/flowtype/flow-for-vscode), the original source of the `which` call, according to the PR comments. Installing the `flow-bin` NPM package on Windows provides you with both a `flow.exe` file and a `flow.cmd` file in different folders (I just tried it), and in that extension, they wanted to make sure that the `which` call located the correct one (the `.cmd`). In Vale's case, there's just the `.exe` file.

**Comment by pedrosousa** [comment]
Just tested it and it works properly now! Thanks
