### ISSUE TITLE
Allow configuring the minAlertLevel would help (or generally additional parameters)

### ISSUE THREAD

**Issue by nkuehn** [errata-ai/vale-vscode#24]
Hi, great to see that the efforts go into one plugin now together. 

Since you merged the workspace path fix, I reactivated our configuration but found that I can't pass additional parameters like `--minAlertLevel suggestion` any more to the vale binary. 

**Use Case:**

Our build tests and GitHub action is not applying suggestion-level rules to not hinder go-live of content that is actually OK in some cases.  But in VSCode we want to show all the suggestion level warnings to encourage and teach better writing style. 

**Potential approaches**

1. explicit config parameter that allows passing a custom minAlertLevel to the binary. 
2. generic possibility to pass additional parameters to the vale binary (would have to be inserted into the parameters array if set). 

What do you think? Does the use case make sense?

**Comment by ChrisChinchilla** [comment]
Hmm, that's odd, I wasn't aware that people were passing in arguments to the command before, but the code was mostly lifted, so there shouldn't be any real reason it isn't still possible.

Just to clarify, how are you trying to pass the argument?

**Comment by nkuehn** [comment]
I appended ` --minAlertLevel suggestion`  to the CLI binary config property, making it the start of a full command instead of jus the binary path.  Maybe the ported code is using node's `child_process.execFile` which then doesn't find a file with that path because it's not a path any more.  `child_process.exec` takes a full command in comparison. 

But messing with the command path isn't necessarily a good thing if the plugin adds vale parameters itself - I once went too far and created unwanted situations with the same parameter being passed multiple times.

**Comment by jdkato** [comment]
I agree that messing the command path isn't the way to go. I think if options are exposed, it should be explicitly through the UI.

**Comment by ChrisChinchilla** [comment]
I do believe this is covered by #14 kind of, but I'll expand that to include arguments too

**Comment by jdkato** [comment]
This will be available in the next release.
