### ISSUE TITLE
Please add .vsix file to the released files

### ISSUE THREAD

**Issue by themr0c** [errata-ai/vale-vscode#26]
Please add .vsix file to the released files, like in precedent incarnation of the plugin, https://github.com/testthedocs/vscode-vale/.

See: https://github.com/testthedocs/vscode-vale/issues/15 

As the VSCode Marketplace license formally prohibits the usage of direct links to the Marketplace for tools other than the official VSCode binary build, other tools using the VSCode extensions need another source to fetch the .vsix files. 

For instance, we use the extension to develop the documentation of Eclipse Che using Eclipse Che. See: https://github.com/eclipse/che-docs/

**Comment by jdkato** [comment]
👍

**Comment by ChrisChinchilla** [comment]
@jdkato You beat me! I think there was a way to automate this 🤔
