### ISSUE TITLE
Publish extension to Open VSX Registry

### ISSUE THREAD

**Issue by ebramirez** [errata-ai/vale-vscode#28]
**Is your feature request related to a problem? Please describe.**
Other IDEs based on Eclipse Theia (The engine behind VS Code) like VSCodium, Eclipse Che, GitPod, etc, use [Open VSX Registry](https://open-vsx.org) instead of the proprietary VS Code Marketplace, so this plugin is not available for those using them.

**Describe the solution you'd like**
I would like that the plugin is deployed to the Open VSX Registry upon release, like it is currently done for the VS Code Marketplace.

The procedure is documented [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by ChrisChinchilla** [comment]
@ebramirez this is done (I am not sure how to confirm it as I don't use the registry), with the latest version of this extension, but I am also working on #32 to make this automatic in the future.

**Comment by ebramirez** [comment]
Hi @ChrisChinchilla,

I can see plugin published in the OpenVSX registry, thanks!

The only issue is that it shows this warning:
![image](https://user-images.githubusercontent.com/42619854/100436924-53936000-30a0-11eb-80f2-5e513ee3fe56.png)

**Comment by ChrisChinchilla** [comment]
@ebramirez Working on that… It's an extra step…

**Comment by ebramirez** [comment]
@ChrisChinchilla Sorry to bother you again with this, but looks like new versions of the plugin are not being pushed to OpenVSX registry.
