### ISSUE TITLE
Extension currently doesn't work in VS Code Insiders

### ISSUE THREAD

**Issue by jdkato** [errata-ai/vale-vscode#36]
This extension currently doesn't work in VS Code Insiders:

> [$extension]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api $extension

**Comment by ChrisChinchilla** [comment]
@jdkato Should it? And do we have any more info on that error message?

**Comment by jdkato** [comment]
Ideally, yes, I think.

The error appears to have originated between v0.7 and v0.8, but I can't say that I understand much more than that at the moment.

And while it's possible that this is a consequence of using an API we need, I'd like to understand it more. 

I'll update the issue when I've had a chance to look into it.

**Comment by ChrisChinchilla** [comment]
I tested, and this seems to work now.
