### ISSUE TITLE
Vscode Extension not working with Vale Server latest release

### ISSUE THREAD

**Issue by ms3056** [errata-ai/vale-vscode#37]
Updated to latest Vale Server and getting this error with the extension in VSCODE:

Vale Server could not connect: RequestError: Error: read ECONNRESET.

**Comment by jdkato** [comment]
Thanks for the report.

Does the server crash when this happens? Does it happen only on certain files?

Could you share the output of the Vale Server console at `Preferences -> Advanced`?
