### ISSUE TITLE
Disable extension on directories without a configuration file

### ISSUE THREAD

**Issue by alexpdp7** [errata-ai/vale-vscode#40]
Hi,

I have added several directories to my VS Code workspace. `vale-vscode` works perfectly on directories with a `.vale.ini` file, but I have several directories for several projects in my workspace that do not use Vale.

`vale-vscode` tries to run `vale` when editing files in such folders, resulting in an error because it cannot find a configuration file.

Can this be controlled in a nice manner? (e.g. without having to add files to the affected directories).

Cheers,

Álex

**Comment by jdkato** [comment]
Are you running the latest version (v0.14.1)? This should have been address recently in #34.

**Comment by alexpdp7** [comment]
Damn, was showing as "reload required". Closing.
