### ISSUE TITLE
Quick Fixes fail intermittently

### ISSUE THREAD

**Issue by jdkato** [errata-ai/vale-vscode#57]
I don't have much information besides the error message below:

<img width="1023" alt="Screen Shot 2021-08-10 at 1 11 26 PM" src="https://user-images.githubusercontent.com/8785025/128929553-13dade85-8157-47c5-aa88-0fccbfe512bc.png">

But it seems to be happening more and more often.

**Comment by ChrisChinchilla** [comment]
Able to reproduce quite quickly, investigating

**Comment by ChrisChinchilla** [comment]
Trying all the updates from #59 didn't seem to fi it

**Comment by ChrisChinchilla** [comment]
If you save the file, and then start applying fixes again, it works again. So maybe some sort of buffer?

**Comment by ChrisChinchilla** [comment]
Some form of the discussion here… https://github.com/hoovercj/vscode-extension-tutorial/issues/1

**Comment by jdkato** [comment]
My logic here:

https://github.com/errata-ai/vale-vscode/blob/6f1c04fa8f467a5935a78b62ad9224ff4f57fdf6/src/features/vsProvider.ts#L229

may be at fault.

Something seems to have changed since I implemented the feature.

**Comment by ChrisChinchilla** [comment]
Hmm, the logic is sound, but it's why you need that that's at fault. If that error is at fault then the "buffer" or range is too out of date and thus even if you remove that check, it starts applying changes where it expects the source of the "wrong" string to be. I am playing with either re-running vale if this check fails, or updating the buffer some other way.
