### ISSUE TITLE
Works in CLI mode but no linting with server mode 

### ISSUE THREAD

**Issue by spacedsweden** [errata-ai/vale-vscode#65]
I set the extensionto use CLI, get linting, using server no lining in markdown or mdx

First time i report so not sure what you need?

extension version: 0.14.2
server version v 1.3

with cli 

![image](https://user-images.githubusercontent.com/1320542/145104519-ade3262f-4f1a-47db-bbf4-71eb34d86523.png)

![image](https://user-images.githubusercontent.com/1320542/145104550-aaabe189-3887-46db-8b09-740ec59a837b.png)

without
![image](https://user-images.githubusercontent.com/1320542/145104578-2d43fed3-a94e-4fe4-920b-00ac2710f1b4.png)
![image](https://user-images.githubusercontent.com/1320542/145104637-aaf56e37-6735-4591-bd10-917261fca170.png)

I get no output from vale that there is any problems

**Comment by jdkato** [comment]
When in Server mode, the results are dependent on your active project (not the local Vale configuration). Do you have a project configured with appropriate settings?

**Comment by spacedsweden** [comment]
sorry for long delay on reply, yeah that did it thanks
