### ISSUE TITLE
Remove Vale Server from code

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-vscode#71]
Vale server is being deprecated, so good time to remove it and streamline the extension whilst at it.

**Comment by michelle-purcell** [comment]
@ChrisChinchilla +1

Does this issue (#71) include removing this option in the Vale extension settings dialogue and making enabling the Vale client CLI by default?

The current extension enables the server by default, which means if you want to use the Vale Client with VS Code or VSCodium, you have to manually configure this option:


![image](https://user-images.githubusercontent.com/92924207/176215663-f91c5ba6-bdf6-4dd2-b9f4-4c9993f62303.png)

Thanks

**Comment by ChrisChinchilla** [comment]
Closed by #78
