### ISSUE TITLE
Provide Quickfix when using Vale CLI

### ISSUE THREAD

**Issue by apupier** [errata-ai/vale-vscode#74]
Given that vale server is planned ot be removed, I think it would be nice to support it for CLI.

Wondering if there's missing feature in Vale CLI or if it is "only" a matter of implementing it in the extension?

**Comment by ChrisChinchilla** [comment]
It's in progress :)

**Comment by apupier** [comment]
might be related to https://github.com/errata-ai/vale/issues/462

**Comment by ChrisChinchilla** [comment]
Closed by #78
