### ISSUE TITLE
Prep release

### ISSUE THREAD

**Issue by jdkato** [errata-ai/vale-vscode#8]
@ChrisChinchilla: I think this is ready for review to be released sometime this week. The changes I made are summarized below:

1. Split settings up into ["groups"](https://code.visualstudio.com/api/references/contribution-points#Configuration-schema): `vale.core.XXX` (both server and CLI), `vale.server.XXX` (server-only), `vale.valeCLI` (CLI-only).

    I also deprecated the `extensions` setting in favor of relying solely on the `.vale.ini`.

   (I know `vale.valeCLI` is kind of an awkward name but, due to VS Code's auto-capitalization, `vale.cli` looks ugly to me.)

2. Pass the current folder to `runInWorkSpace` (https://github.com/errata-ai/vale-vscode/commit/1501ba5a28c7d039f301ccc5e877fba9c564aea7). This allows Vale to find a config file itself, if one isn't provided (the default behavior).

3. Set `vale.valeCLI.path` to `null` by default. You originally had it set `vale` as the default value, but I think this was probably just for testing?

4. Add a few server-only commands for interacting with vocab-related files (`vale.addToAccept`, `vale.addToReject`, `vale.openAccept`, `vale.openReject`).

Thanks!

(Once we're all clear here, I'll also update the README to reflect the latest changes.)

**Comment by ChrisChinchilla** [comment]
> Split settings up into "groups": vale.core.XXX (both server and CLI), vale.server.XXX (server-only), vale.valeCLI (CLI-only).

Didn't know that was possible, cool.

> I also deprecated the extensions setting in favor of relying solely on the .vale.ini.

I seem to remember that being necessary so VSCode knows what files to trigger on, but I assume you tested it still works on a variety of files? Or I guess you can load the value from the ini file?

> Set vale.valeCLI.path to null by default. You originally had it set vale as the default value, but I think this was probably just for testing?

Not sure now, again I guess you tested that it still works if there is no value set?

> (Once we're all clear here, I'll also update the README to reflect the latest changes.)

Yes, also there was a changelog in the old extension, not sure there is one here. I don't mind really.

Then I'll add depreciation notices to the old extension once i've run this one for a week or so (for "real world testing") and move over some enhancement ideas I have.

**Comment by jdkato** [comment]
> I seem to remember that being necessary so VSCode knows what files to trigger on, but I assume you tested it still works on a variety of files? Or I guess you can load the value from the ini file?

I changed the [`activationEvents`](https://code.visualstudio.com/api/references/activation-events#Start-up) setting to `*`, which means the extension will activate on start-up rather than on certain file types. And then the results are determined by the active `.vale.ini`.

> Not sure now, again I guess you tested that it still works if there is no value set?

My understanding is that, when no value is set, it uses the location from the `$PATH`. When a value is set, it simply uses that. This seems to work as expected in my testing (whereas with a default of `vale`, my custom `$PATH` had to be added manually).

**Comment by ChrisChinchilla** [comment]
OK, well if you tested both, then fine with me.

**Comment by jdkato** [comment]
It's out now.
