### ISSUE TITLE
Running extension on Windows: vale not found

### ISSUE THREAD

**Issue by Jc-L** [errata-ai/vale-vscode#94]
I am trying to set up the vale extension on Windows and get the following error in VS Code (command line works fine) :

`There was an error running Vale Error: not found: vale.`

I did set up `vale.path` to the correct values, with `/` or `\` separators, with or without the `.exe` extension; with or without the executable name, without success. The comment that `.cmd` extension can be omitted raises questions, as I have no `vale.cmd` anywhere in my setup.

Am I missing something ?

Visual Studio Code version 1.69.2
Extension version 0.15.0
Vale version 2.20.1

**Comment by apupier** [comment]
i think you hit this regression https://github.com/errata-ai/vale-vscode/issues/90

**Comment by abtxu** [comment]
Same thing happened to me. Tried lots of times to save the configuration of extension. Not working at all. 
Tried to edit the defaultsetting.json of vscode, failed.

**Comment by abtxu** [comment]
My solution:
Step1: VScode extension page→uninstall→install another version, say v0.14.2, and this will bring back the oder config interface of vale.
Step2: Put in the path of .vale.ini and vale.exe.
Step3: Update to v0.15.0, which adopts the v0.14.2 config.

**Comment by Jc-L** [comment]
@abtxu Than k you for the suggestion. Unfortunately the suggestion did not help. I see the different options in the `settings.json` file and the error is still present. Running manually works well.

```
    "vale.config": "C:\\Users\\jcl\\.vale.ini",
    "vale.path": "C:\\Users\\jcl\\homedir-git\\bin\\vale.exe",
    "vale.valeCLI.config": "C:\\Users\\jcl\\homedir-git\\bin\\vale.exe"
```
